### ISSUE TITLE
Adapt code to work with the commented sensors

### ISSUE THREAD

**Issue by Tijunel** [SchulichRacingElectrical/SchulichVelocity2.0#75]
Here is a list of all of the sensors:
1) TPS
2) MAP
3) IAT
4) Fuel Temp
5) Oil Temp
6) Oil Pressure
7) CTS (Engine Temp)
8) EGT (Exhaust Temp) (4 Data values)
9) O2 Sensor
10) Cam Position
11) Crank Position
12) Neutral Switch
13) Brake Pressure
14) Wheel Speed (FR, FL, RR, RL)
15) Potentiometers (FR, FL, RR, RL)
16) Rotary Pot
17) Pressure Transducer (2 Sensors)

**Comment by JeremyBilic** [comment]
Sensors added
